<a href="https://colab.research.google.com/github/gaoyanxie/Hello/blob/master/PyTorch_Grad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.cuda.is_available())

True


In [36]:
in_data = [[1.,2.],[3.,4.]]
in_tensor = torch.tensor(in_data)
w_data = [[1.,2],[1.1,2.2],[1.3,2.3],[1.4,2.4]]
w_tensor = torch.tensor(w_data)
out_data = [[2.,4,2,4],[6.,8,6,8]]
out_tensor = torch.tensor(out_data)

class MyModel(torch.nn.Module):
  def __init__(self):
    super(MyModel, self).__init__()
    self.wo = torch.nn.Linear(2,2) #torch.nn.Sigmoid()
    self.fc = torch.nn.Linear(2, 4)#torch.matmul 
  def forward(self, x, w):
    w_out = self.wo(w)
    #w_out = torch.transpose(w_out, 0, 1)
    weight = torch.nn.Parameter(w_out)
    self.fc.weight = weight
    out = self.fc(x)#self.fc(x, self.weight)
    return out

m = MyModel()    
#print(m.fc.weight)
pred = m(in_tensor, w_tensor)
loss = (out_tensor - pred).sum()
print(m.wo.weight)
print(m.fc.weight)
print(loss)
#print(m.fc.weight)
loss.backward()
print(m.wo.weight.grad)
print(m.fc.weight.grad)

Parameter containing:
tensor([[-0.0259, -0.1394],
        [ 0.2041,  0.1205]], requires_grad=True)
Parameter containing:
tensor([[0.1001, 0.3866],
        [0.0696, 0.4311],
        [0.0505, 0.4840],
        [0.0340, 0.5165]], requires_grad=True)
tensor(29.3354, grad_fn=<SumBackward0>)
None
tensor([[-4., -6.],
        [-4., -6.],
        [-4., -6.],
        [-4., -6.]])


In [30]:
optim = torch.optim.SGD(m.parameters(), lr=1e-2, momentum=0.9)
optim.step()
print(m.wo.weight)

Parameter containing:
tensor([[0.3026, 0.5287],
        [0.1818, 1.0705]], requires_grad=True)


In [31]:
pred = m(in_tensor, w_tensor)
loss = (out_tensor - pred).sum()
print(m.weight)
print(loss)
loss.backward()
print(m.wo.weight.grad)

tensor([[2.1148, 2.2508, 2.3642, 2.4473],
        [2.8270, 3.0593, 3.2027, 3.3280]], grad_fn=<TransposeBackward0>)
tensor(-71.2105, grad_fn=<SumBackward0>)
tensor([[ -38.4000,  -71.2000],
        [ -57.6000, -106.8000]])


In [32]:
optim.step()
print(m.wo.weight)

Parameter containing:
tensor([[0.8594, 1.5611],
        [1.0170, 2.6191]], requires_grad=True)


In [33]:
pred = m(in_tensor, w_tensor)
loss = (out_tensor - pred).sum()
print(m.weight)
print(loss)
loss.backward()
print(m.wo.weight.grad)

tensor([[5.2004, 5.5985, 5.9265, 6.1686],
        [7.4554, 8.0810, 8.5463, 8.9099]], grad_fn=<TransposeBackward0>)
tensor(-249.5315, grad_fn=<SumBackward0>)
tensor([[ -57.6000, -106.8000],
        [ -86.4000, -160.2000]])
